Repository Umuhasna/AirBnB_clone, pull requests merged in 2023-08, with the labels that each got.

#15 Title: Added Authors
  AUTHORS
Labels: enhancement

#16 Tasks/task 3
  models/__init__.py
  models/base_model.py
  tests/test_models/__init__.py
  tests/test_models/test_base_model.py
Labels: bug, documentation, enhancement

#17 Title: Task 4
  models/__pycache__/__init__.cpython-311.pyc
  models/__pycache__/base_model.cpython-311.pyc
  models/base_model.py
  test_base_model_dict.py
Labels: enhancement

#20 Tasks/task 5
  file.json
  models/__init__.py
  models/__pycache__/__init__.cpython-311.pyc
  models/__pycache__/base_model.cpython-311.pyc
  models/base_model.py
  models/engine/.file_storage.py.swp
  models/engine/__init__.py
  models/engine/__pycache__/__init__.cpython-311.pyc
  models/engine/__pycache__/file_storage.cpython-311.pyc
  models/engine/__pycache__/file_storage.cpython-38.pyc
  models/engine/file_storage.py
  test_save_reload_base_model.py
Labels: enhancement

#21 Fixed pycodestyle error
  models/engine/file_storage.py
Labels: bug

#22 Created a test file
  tests/test_models/test_file_storage.py
Labels: documentation

#23 Add some Documentation tests
  tests/test_models/test_file_storage.py
Labels: documentation, enhancement

#24 Fix pycodestyle error
  tests/test_models/test_file_storage.py
Labels: bug

#26 Title: Fix
  models/engine/file_storage.py
Labels: bug, enhancement

#28 Title: Task 8, 9 and 10
  console.py
  file.json
  models/__init__.py
  models/__pycache__/__init__.cpython-311.pyc
  models/__pycache__/amenity.cpython-311.pyc
  models/__pycache__/base_model.cpython-311.pyc
  models/__pycache__/city.cpython-311.pyc
  models/__pycache__/place.cpython-311.pyc
  models/__pycache__/review.cpython-311.pyc
  models/__pycache__/state.cpython-311.pyc
  models/__pycache__/user.cpython-311.pyc
  models/amenity.py
  models/city.py
  models/engine/__pycache__/__init__.cpython-311.pyc
  models/engine/__pycache__/file_storage.cpython-311.pyc
  models/engine/file_storage.py
  models/place.py
  models/review.py
  models/state.py
  models/user.py
  test_base_model_dict.py
  test_save_reload_base_model.py
  test_save_reload_user.py
Labels: enhancement

#29 Title: Task 11
  console.py
  models/__pycache__/__init__.cpython-311.pyc
  models/__pycache__/amenity.cpython-311.pyc
  models/__pycache__/city.cpython-311.pyc
  models/__pycache__/place.cpython-311.pyc
  models/__pycache__/review.cpython-311.pyc
  models/__pycache__/state.cpython-311.pyc
  models/__pycache__/user.cpython-311.pyc
  models/engine/__pycache__/file_storage.cpython-311.pyc
  models/engine/file_storage.py
Labels: enhancement

#30 Title: Fix All classes for Task 11
  console.py
  models/engine/__pycache__/file_storage.cpython-311.pyc
Labels: bug

#31 Title: Fix Task 12 Count
  console.py
  models/engine/__pycache__/file_storage.cpython-311.pyc
Labels: bug, enhancement

#32 Title: Task 13 done
  console.py
Labels: enhancement

#33 Title: Task 14
  console.py
  file.json
Labels: enhancement

#34 Title: Task 14 Fix
  console.py
Labels: bug, enhancement

#36 Title: Add
  tests/test_models/test_amenity.py
  tests/test_models/test_city.py
  tests/test_models/test_place.py
  tests/test_models/test_review.py
Labels: documentation, enhancement

#38 Tasks/task 17
  __init__.py
  __pycache__/console.cpython-311.pyc
  file.json
  tests/__pycache__/test_console.cpython-311.pyc
  tests/test_console.py
Labels: enhancement

#41 Tasks/task 2
  tests/__init__.py
  tests/test_models/test_engine/__init__.py
Labels: enhancement
